extends Node


func _ready():
	# randomize the randon generator seed
	randomize()


func generate_blocks():
	# get the number of child nodes
	var child_count = get_child_count()
	# get a random value between 0 and child count
	var index = rand_range(0, child_count)
	# get the node at the randomly selected index
	var factory = get_child(index)
	# return the blocks generated by the selected factory node
	return factory.generate_blocks()

